### ISSUE TITLE
Does not compile on Mac OS X 11.3.1

### ISSUE THREAD

**Issue by rheinonen** [trey0/zmdp#3]
When I try to compile on my Mac, I get the error

"[parent directory]/zmdp/include/zmdpCommonTypes.h:54:14: error: static_cast from 'zmdp::MDPNode *' to 'size_t' (aka 'unsigned long') is not allowed 
return h(static_cast<size_t>(p));"

followed by some more info which I can provide if desired.

**Comment by trey0** [comment]
Ok, fixed in https://github.com/trey0/zmdp/commit/d07d4f92479b92a56f955d464837fcce89085ebf .

It looks like recent Xcode g++ versions that support C++11 still report an ancient version number, so some code to auto-detect what version of a standard library data structure to use (hash_map / unordered_map) was fooled. After my crude fix it probably won't compile on older Xcode versions, but likely nobody is trying to do that anyway.

My main laptop is a Mac, but I still prefer to develop software in a Linux VM. If you continue to have problems you might want to try it in a Linux VM or use the Docker build.

**Comment by rheinonen** [comment]
Great, thanks for the quick fix!
